version: '3.5'

# Services for testing and running the application locally
services:
  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
