ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = 1
warningCode = 0
enableAllRules = true

[rule.context-keys-type]
  Disabled = true
[rule.dot-imports]
  Disabled = true
[rule.exported]
  Disabled = true
[rule.package-comments]
  Disabled = true
[rule.line-length-limit]
  Arguments = [120]
[rule.add-constant]
  Disabled = true
[rule.max-public-structs]
  Disabled = true
[rule.cognitive-complexity]
  Arguments = [40]
[rule.cyclomatic]
  Arguments = [40]
[rule.function-length]
  Disabled = true
# [rule.receiver-naming]
# [rule.time-naming]
# [rule.unexported-return]
# [rule.indent-error-flow]
# [rule.errorf]
# [rule.empty-block]
# [rule.superfluous-else]
# [rule.unused-parameter]
# [rule.unreachable-code]
# [rule.redefines-builtin-id]